CREATE TABLE webos_metatags(meta_id int IDENTITY(1,1) NOT NULL,
meta_subject varchar(1500) NOT NULL CONSTRAINT DF__webos_met__meta___30F848ED  DEFAULT (''),
meta_description varchar(1800) NOT NULL CONSTRAINT DF__webos_met__meta___31EC6D26  DEFAULT (''),
meta_keywords varchar(1800) NOT NULL CONSTRAINT DF__webos_met__meta___32E0915F  DEFAULT (''),
meta_language varchar(150) NOT NULL CONSTRAINT DF__webos_met__meta___33D4B598  DEFAULT (''),
meta_expires varchar(150) NOT NULL CONSTRAINT DF__webos_met__meta___34C8D9D1  DEFAULT (''),
meta_abstract varchar(1500) NOT NULL CONSTRAINT DF__webos_met__meta___35BCFE0A  DEFAULT (''),
meta_site_name varchar(1500) NULL,
meta_revisit varchar(50) NULL,
meta_distribution varchar(150) NOT NULL CONSTRAINT DF__webos_met__meta___37A5467C  DEFAULT (''),
meta_bots varchar(150) NOT NULL CONSTRAINT DF__webos_met__meta___38996AB5  DEFAULT (''),
meta_googlebot varchar(150) NOT NULL CONSTRAINT DF__webos_met__meta___398D8EEE  DEFAULT (''),
meta_msnbot varchar(150) NOT NULL CONSTRAINT DF__webos_met__meta___3A81B327  DEFAULT (''),
CONSTRAINT PK__webos_metatags__300424B4 PRIMARY KEY CLUSTERED (meta_id ASC) )