CREATE TABLE webos_users(
Id varchar(35) NOT NULL,
firstname varchar(150) NULL,
lastname varchar(150) NULL,
username varchar(50) NOT NULL DEFAULT (''),
password varchar(50) NOT NULL DEFAULT (''),
emailaddress varchar(255) NOT NULL DEFAULT (''),
datecreated datetime NOT NULL DEFAULT (getdate()),
signature varchar(500) NULL,
avatar_url varchar(255) NULL DEFAULT (''),
location varchar(50) NULL DEFAULT (''),
confirmed smallint NOT NULL DEFAULT (''),
active smallint NOT NULL DEFAULT ((1)),
inactive_reason varchar(255) NULL DEFAULT (''),
use_gravatar smallint NOT NULL DEFAULT (''),
flag_admin smallint NOT NULL DEFAULT (''),
website varchar(255) NULL DEFAULT (''),
hide_email smallint NOT NULL DEFAULT ((1)),
timezone varchar(30) NULL DEFAULT(''),
accept_pm smallint NOT NULL DEFAULT ((1)),
moderate_posts smallint NOT NULL DEFAULT ((0)),
admin_comments text NOT NULL DEFAULT (''),
newsletter_sign_up int NULL DEFAULT ((0)),
blog_sign_up int NULL DEFAULT ((0)),
age varchar(50) NULL DEFAULT (''),
sign_up_date datetime NULL DEFAULT (''),
PRIMARY KEY CLUSTERED (Id ASC) )  